version: '3.3'
services:
        web:
            build:
                context: ./
            container_name: php-apache
            depends_on:
                - db
            volumes:
                - ./src:/var/www/html/
            ports:
                - 8000:80
        db:
            image: mysql:8.0
            volumes:
              - db_data:/var/lib/mysql
            container_name: mysql
            command: --default-authentication-plugin=mysql_native_password
            restart: always
            environment: 
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: database
                MYSQL_USER: user
                MYSQL_PASSWORD: password
            ports:
                - 3306:3306
                
volumes:
    db_data:
